### ISSUE TITLE
(Native) English proofreading 

### ISSUE THREAD

**Issue by willdurand** [TailorDev/franklin#116]
Hi!

As non-native English speakers/writers, we are looking for people willing to proofread the `CONTRIBUTING` and `README` files.

Thank you for your help ❤️ 

---

**PLEASE:** leave a comment here to let everyone knows that you are working on this issue, **before** submitting a PR!

**Comment by schott12521** [comment]
I'm going through your `CONTRIBUTING` file right now and see a few changes that can be made!

**Comment by yrahul3910** [comment]
I'm looking through the files to check for something I can fix.

**Comment by willdurand** [comment]
Hi @yrahul3910, could you rather review @schott12521's PR here: #117? Thanks!

**Comment by yrahul3910** [comment]
The proofreading by @schott12521 matches what I had changed, so I'll work on proofreading the `README` file. :)

**Comment by gauravdesale** [comment]
I will do this too where can i find the read me file

**Comment by willdurand** [comment]
This is issue is solved, thanks everyone!
