### ISSUE TITLE
Loading (large) file causes important perf. issues

### ISSUE THREAD

**Issue by willdurand** [TailorDev/franklin#21]
Hi.

I tried to drop a larger file (6MO) than usual ([pseudomonas_aeruginosa.fna.txt](https://github.com/TailorDev/franklin/files/293587/pseudomonas_aeruginosa.fna.txt)). My web browser crashed several times.

I implemented a chunk-based file reader so that it can handle large files. So far so good, it reads file per chunks, and I can even update the state (`sequence`). **But**, the way the app is designed causes huge performance issues.

Every time the sequence changes in the state, the `Sequence` component updates, _i.e._ each `Nucleotide` is updated, that is rendered again. The more nucleotides, the more updates. Let's take an example:

```
// the complete sequence (better with different chars)
ABCDEF
```

Assuming we have chunks of two chars, we get three chunks: `AB`, `CD`, `EF`. Now, let's start reading this sequence. We start by creating a list containing `[A, B]`, which is passed to the `Sequence` component. We have two `Nucleotide` components.

Now, we read a new chunk `CD`, the sequence list gets updated (`[A, B, C, D]`), which forces the `Sequence` component to re-render itself. We create two new `Nucleotide` components **and** we update the two previous ones.

Now, we read a new chunk `EF`. Same thing. We create two new `Nucleotide` components **and we update the four previous ones**.

Now let's think about this issue with larger sequences. Things start to be pretty bad. Reading a large file is not an issue _per se_, but rendering the sequence is a nightmare. Either we can render the `Sequence` component once, or we need to avoid existing `Nucleotide` ones to update.

Last but not least, it affects memory consumption :-( This makes me think that loading the whole sequence is not the best thing we can do, yet we don't have any better alternative. Also, combining the number of nucleotides with SVG drawbacks might be even worse.

Not sure what to do right now to be honest. I am pretty sure we can, somehow, fix such an issue but I don't know how yet. I need to think about it.

**Comment by willdurand** [comment]
So, with recent changes we still have an issue for loading 6Mbp.

**Comment by jmaupetit** [comment]
It's an edge case for me. For now, I am not sure we have to care about this.

**Comment by willdurand** [comment]
Agreed.
