### ISSUE TITLE
Add a 'Clear selection' button

### ISSUE THREAD

**Issue by jmaupetit** [TailorDev/franklin#32]
## Purpose

Right now, it is possible to "clear" a selection by using <kbd>esc</kbd> or by double clicking on the same nucleotide (a letter), but we need to be able to easily clear the current selection with a button on the interface. 

## Proposal

Let's add a `Clear current selection` sentence (with a nice "cross" icon) below the search bar. This sentence should be a **link**. When we click on the link, it should trigger the "clear selection" event (similar to [this](https://github.com/TailorDev/franklin/blob/0370dc12a5753754db0e243408325dcb728b678b/app/components/App.jsx#L57)). This link should only be displayed when there is a selection (or at least, it should be disabled).

![screen shot 2016-09-29 at 15 34 19](https://cloud.githubusercontent.com/assets/217628/18956112/85c831b2-865a-11e6-9311-9ed9c049db00.png)

---
Updated by @willdurand on 2016-09-29.

**Comment by lodelestra** [comment]
hi,
> "Let's add a Clear current selection sentence (with a nice "cross" icon) below the search bar. This sentence should be a link."

A link or a button with a cross icon? like this?

<img width="606" alt="screen shot 2016-10-03 at 11 23 39" src="https://cloud.githubusercontent.com/assets/10141712/19032888/8b160d6a-895c-11e6-81ab-9f375ee5caac.png">

**Comment by willdurand** [comment]
Hi @lodelestra, I think a link would be enough if we can make it visible.

**Comment by willdurand** [comment]
Done in #120
