### ISSUE TITLE
jsx-no-bind error

### ISSUE THREAD

**Issue by lodelestra** [TailorDev/franklin#41]
Error thrown at building and runtime.
With eslint-plugin-react@5.2.2 

```
ERROR in ./app/components/Sequence.jsx
[...]
19:32  error  JSX props should not use .bind()  react/jsx-no-bind

✖ 1 problem (1 error, 0 warnings)
```

This error doesn't appear with eslint-plugin-react version 5.1.1.

**Comment by willdurand** [comment]
Yup, caused by: https://github.com/yannickcr/eslint-plugin-react/issues/474. Let's see what we did here...

**Comment by willdurand** [comment]
Indeed, we should have bound the `handleNucleotideClick` function to `this` in the constructor (cf. https://github.com/TailorDev/franklin/blob/master/app/components/Sequence.jsx#L19)
