### ISSUE TITLE
Deal with upload of weird/empty/partial files

### ISSUE THREAD

**Issue by willdurand** [TailorDev/franklin#70]
## Purpose

The general idea is to tell users when something went wrong with their sequence files (and maybe other issues later). In my opinion, we should have a notification component (à la Monod for instance) to deal with such messages, but a first iteration would be to be able to display nice alert boxes to the users.
## Features

The first potential errors to deal with are the following:
- [x] upload of an empty file
  
  File content example:
  
  ```
  ```
  
  => User should be warned that the file was empty, and that we did not set up anything
- [x] upload of a file with only a header (`> foo`)
  
  File content example:
  
  ```
   > foo
  ```
  
  => Same resolution as above.
- [x] upload of a file without a name/any info (header = `>`), but there is a sequence
  
  File content example:
  
  ```
   >
   ATCG
  ```
  
  => The sequence should be loaded and the "name" should be set to "unknown".

**Comment by jmaupetit** [comment]
Do we need to add notifications support for this?

**Comment by willdurand** [comment]
I slightly improved this issue description ):

**Comment by lodelestra** [comment]
Hi!
Can I take this one?

**Comment by willdurand** [comment]
Sure. You're assigned now!

**Comment by willdurand** [comment]
Fixed!
